<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/04/14 02:17:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mexmov',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
